### ISSUE TITLE
Love the Subset idea! 

### ISSUE THREAD

**Issue by davidgasquez** [subsetsio/subsets-connectors#49]
Heya @nathansnellaert! I'm David and just came across this. 

Wanted to reach out and say that I was very happy to came across Subsets. For the last two years, I've been working on a similar thing, [Datadex](https://github.com/davidgasquez/datadex) (a bit outdated now), which has become a pattern I'm applying to [Open Data Portals](https://github.com/davidgasquez/gitcoin-grants-data-portal).

The idea with Datadex was to make a data warehouse of public data and then build an Data IDE that could suggest "smart" enhancements to the data you upload (E.g: Country + Year -> GDP). Useful for ML! I think you might be trying something similar?

I've been also exploring how to [integrate with the Open Data landscape](https://github.com/datonic) (package managers, owid datasets, ...) in a smart way to avoid duplicating work.

Anyway, I'd love to chat as I've been [thinking about Open Data](https://publish.obsidian.md/davidgasquez/Open+Data) for a while now and seems we're also using the same tools/techniques! If all of this sounds interesting to you, [please reach out](https://davidgasquez.github.io/)!

**Comment by davidgasquez** [comment]
I was re-reading my notes on the _Open Data IDE_ and spotted this change 2 years ago:

https://github.com/davidgasquez/handbook/blame/main/Open%20Data.md#L317

I feel that might have been you? :sweat_smile:

**Comment by nathansnellaert** [comment]
Hey @davidgasquez! Thanks so much for reaching out. 

That was us indeed! We started as an enrichment API for ML, but found that pretty much every data consumer was having accessibility problems, so now we are focussing on the platform layer.

Datadex looks awesome. We want to make our offering easily accessible outside the centralised BigQuery warehouse, and the stack you chose there looks very promising!

Your obsidian is an absolute gold mine. You highlight the problems with the current open data landscape so well, and there's some really interesting technologies that could be super useful for subsets. Would love to chat more, reaching out to you :)
